src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import  path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name='posts'

urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('detail/<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('update/<str:slug>', BlogPostUpdate.as_view(), name='edit'),
    path('delete/<str:slug>', BlogPostDelete.as_view(), name='delete'),

]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Titre')
    slug = models.SlugField(max_length=255, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(blank=True, null=True)
    published = models.BooleanField(default=True, verbose_name='Publié')
    content = models.TextField(blank=True, verbose_name='contenu')
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Article'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post', kwargs={"slug": self.slug})

    @property
    def author_or_default(self):
        return self.author.username if self.author else 'auteur inconu'

src/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from posts.models import BlogPost


class BlogHome(ListView):
    model = BlogPost
    # queryset = BlogPost.objects.filter(published=True)
    context_object_name = 'posts'
    template_name = 'posts/blog_posts.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)


@method_decorator(login_required, name='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    fields = ['title', 'content']


@method_decorator(login_required, name='dispatch')
class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_edit.html'
    context_object_name = 'post'
    fields = ['title', 'content', 'published']


class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = 'posts/blog_posts _detail.html'
    context_object_name = 'post'


@method_decorator(login_required, name='dispatch')
class BlogPostDelete(DeleteView):
    model = BlogPost
    template_name = 'posts/blog_posts _delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('posts:home')

src/posts/templates/posts/blog_posts _delete.html
{% extends 'base.html' %}


{% block title %} <title>Supression</title> {% endblock title %}


{% block content %}

<form  method="POST">
    {% csrf_token %}
    <p>Ete vous sur de vouloire supprimer {{ post }} ?</p>
    <input type="submit" value="Suprimer" class="btn btn-delete">
</form>


{% endblock content %}

src/posts/templates/posts/blog_posts _detail.html
{% extends 'base.html' %}


{% block title %} <title>{{ post.title }}</title> {% endblock title %}


{% block content %}


<article class="post-detail">
    <h1> {{ post.title }} </h1>
    <img src="{{ post.thumbnail.url }}" alt="Image de l'article" height="350px" >
    <div> {{ post.content|safe|linebreaks }} </div>
</article>


{% endblock content %}

src/posts/templates/posts/blog_posts.html
{% extends 'base.html' %}


{% block title %} <title>Accueil du blob</title> {% endblock title %}


{% block content %}

<h1>Le blog de lane</h1>

{% for post in posts %}

<article>
    <div class="post-title" >
        <h2> {{ post.title }} </h2>
        {% if request.user.is_authenticated %}
        <div>
            <a href="{% url 'posts:edit' slug=post.slug  %}"> Editer</a>
            <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
        </div>
        {% endif %}
    </div>


    <h5 class="post-author " >Publié par <i> {{ post.author_or_default }} </i> le {{ post.created_on|date:'j F Y' }} </h5>
    <p class="post-excerpt "> {{ post.content|safe|truncatewords:20 }} </p>
    <form action="{{ post.get_absolute_url }}">
        <button class="btn btn-submit">Lire l'article</button>
    </form>
</article>


{% empty %}{% endfor %}

{% endblock content %}

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}


{% block title %}
    <title>Ajouter un artile </title>
{% endblock title %}


{% block content %}

<h1>Créer une article </h1>

<form method="POST">
    {% csrf_token %}
    <p>
        <input type="text" name="title" id="" placeholder="Titre">
    </p>
    <p>
        <textarea name="content" id="" cols="30" rows="10"></textarea>
    </p>
    <input type="submit" value="Créer" class="btn btn-submit">
    
</form>

{% endblock content %}

src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}


{% block title %}
    <title>Eiter un artile </title>
{% endblock title %}


{% block content %}

<h1>Editer l'article</h1>


<form method="POST">
    {% csrf_token %}

    <label for="title">Titre</label>
    <input type="text" name="title" id="" value="{{ post.title }}" >

    <label for="content">Contenu</label>
    <textarea name="content" id="" cols="30" rows="10"> {{ post.content }} </textarea>

    <label for="published">Publiée</label>
    <input type="checkbox" name="published" id="" >

    <input type="submit" value="Editer" class="btn btn-submit">
    
</form>

{% endblock content %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Accueil du blog</title>
    {% endblock title %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <a href="{% url 'posts:home' %}">Accueil</a> 
        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create' %}">Ajouter un article</a> 
        {% endif %}
    </nav>
    <section id='blog'>
        {% block content %}{% endblock content %}
    </section>
    
</body>
</html>